logging:
  level:
    root: error
spring:
  mvc:
    ### 让mvc直接抛出异常，在全局异常类，捕获404 异常的类 NoHandlerFoundException.class
    throw-exception-if-no-handler-found: true
  ### 关闭资源映射
  resources:
    add-mappings: false

server:
  port: 1000

apps:
  appList:
    - appName: ht
      clientID: amzn1.application
      clientSecret: 8c934d496
      appID: amzn1.sp.solution.


    - appName: yt
      clientId: amzn1.application-
      clientSecret: 479a129ca10873b5
      appId: amzn1.sp.solution.
